version: '3'

services:
  dofins_database:
    image: postgres:16.2-alpine3.19
    container_name: dofins_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dofins
    volumes:
        - ./dofins_database:/var/lib/postgresql/data
    ports:
        - 5432:5432
    healthcheck:
            test: ["CMD-SHELL","pg_isready"]
            interval: 3s
            timeout: 20s
            retries: 8
  
  dofins_redis:
    image: redis:latest
    restart: always
    ports:
        - '6739:6739'
      
    healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 3s
        timeout: 20s
        retries: 8
  

   
  #dofins_nginx:
   # build:
   #         context: .
    #        dockerfile: Donfins/Nginx
    #restart: always
    #volumes:
    #    - ./config/nginx.conf:/etc/nginx/nginx.conf
     #   - ./ssl:/etc/nginx/ssl
    #ports:
     #   - "80:80"
      #  - "443:443"
    #depends_on:
     #   - dofins 